# 1.Veride olup, 2.Veride olmayan hastaneler ve atamalar:

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("https://raw.githubusercontent.com/hasanbarisgok/DataScience/main/projects/hemsirelik_atama/main/result_csvs/birinci_klavuz_tum.csv")
df2 = pd.read_csv("https://raw.githubusercontent.com/hasanbarisgok/DataScience/main/projects/hemsirelik_atama/main/result_csvs/ikinci_klavuz_tum.csv")

In [3]:
mask = ~df1['HOSPITALS'].isin(df2['HOSPITALS'])
result = df1[mask]

In [4]:
result.head()

,Unnamed: 0,HISTORY,HOSPITALS,CITIES,TOTAL QUOATA,VACANT,LOWEST POINT,HIGHEST POINT,REGIONS
9,9,1.12.2020,Gümüşhane Kelkit İlçe Sağlık Müd.,Gümüşhane,1,0,"80,62","80,62",Karadeniz Bölgesi
10,10,1.12.2020,Gümüşhane Merkez TSM.,Gümüşhane,1,0,"85,01","85,01",Karadeniz Bölgesi
12,12,1.12.2020,Narman İlçe Devlet Hast.,Erzurum,1,0,"74,21","74,21",Doğu Anadolu Bölgesi
14,14,1.12.2020,Şenkaya İlçe Devlet Hast.,Erzurum,1,0,"74,41","74,41",Doğu Anadolu Bölgesi
15,15,1.12.2020,Olur İlçe Devlet Hast.,Erzurum,1,0,"74,47","74,47",Doğu Anadolu Bölgesi

In [5]:
result = result.drop(columns = ["Unnamed: 0", "VACANT"], axis = 1)
result = result.rename(columns = {"TOTAL QUOATA":"QUOATA","LOWEST POINT":"MIN","HIGHEST POINT":"MAX"})

In [6]:
result = result.sort_values(by = ["CITIES", "HOSPITALS"])

In [7]:
result = result.reset_index(drop=True)

In [8]:
result.head()

,HISTORY,HOSPITALS,CITIES,QUOATA,MIN,MAX,REGIONS
0,1.12.2020,Adana Dr.Ekrem Tok Ruh Sağ.ve Has. Hastanesi,Adana,8,"81,17","86,3",Akdeniz Bölgesi
1,1.12.2020,Adana Seyhan Devlet Hast.,Adana,38,"81,66","91,93",Akdeniz Bölgesi
2,1.12.2020,Ankara 29 Mayıs Devlet Hast.,Ankara,2,88,"92,38",İç Anadolu Bölgesi
3,1.12.2020,Ankara Atatürk Göğüs Hastal.ve Göğüs Cer. EAH.,Ankara,97,"75,77","84,18",İç Anadolu Bölgesi
4,1.12.2020,Ankara Beytepe Murat Erdi Eker Devlet Hast.,Ankara,2,"88,16","89,63",İç Anadolu Bölgesi

In [9]:
result.describe().T

        count      mean        std  min  25%  50%  75%    max
QUOATA  164.0  8.329268  15.770637  1.0  1.0  2.0  8.0  114.0

In [10]:
result.to_csv("sadece_birinci_klavuzdaki_hastaneler.csv", index = False)

# 2.Veride olup, 1.Veride olmayan Hastaneler ve Atamalar

In [11]:
mask_second = df2['HOSPITALS'].isin(df1['HOSPITALS'])
result_second = df2[mask_second]

In [12]:
result_second.head()

,Unnamed: 0,HISTORY,HOSPITALS,CITIES,QUOATA,MIN,MAX,REGIONS
19,19,16.12.2021,Yalvaç Devlet Hast.,Isparta,3,"76,05","76,69",Akdeniz Bölgesi
20,20,16.12.2021,Sütçüler İlçe Devlet Hast.,Isparta,1,"76,35","76,35",Akdeniz Bölgesi
22,22,16.12.2021,Senirkent İlçe Devlet Hast.,Isparta,1,"76,46","76,46",Akdeniz Bölgesi
23,23,16.12.2021,Uluborlu İlçe Devlet Hast.,Isparta,1,"77,44","77,44",Akdeniz Bölgesi
25,25,16.12.2021,Gelendost İlçe Devlet Hast.,Isparta,1,"79,07","79,07",Akdeniz Bölgesi

In [13]:
result_second = result_second.drop("Unnamed: 0", axis = 1)

In [14]:
result_second = result_second.sort_values(by= ["CITIES", "HOSPITALS"])

In [15]:
result_second = result_second.reset_index(drop = True)

In [16]:
result_second.head()

,HISTORY,HOSPITALS,CITIES,QUOATA,MIN,MAX,REGIONS
0,16.12.2021,Adana Yüreğir Devlet Hast.,Adana,5,"78,63","81,36",Akdeniz Bölgesi
1,16.12.2021,Adana Şehir Hast.,Adana,68,"78,73","86,24",Akdeniz Bölgesi
2,16.12.2021,Tufanbeyli Devlet Hast.,Adana,7,"74,55","76,91",Akdeniz Bölgesi
3,16.12.2021,İmamoğlu Devlet Hast.,Adana,1,"80,38","80,38",Akdeniz Bölgesi
4,16.12.2021,Gerger İlçe Devlet Hast.,Adıyaman,2,"78,47","78,53",Güneydoğu Anadolu Bölgesi

In [17]:
result_second.describe().T

        count       mean        std  min  25%  50%   75%    max
QUOATA  453.0  10.267108  24.499083  1.0  2.0  3.0  10.0  353.0

In [18]:
result_second.to_csv("sadece_ikinci_klavuzdaki_hastaneler.csv", index = False)